server:
  port: 18082
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8720
  zipkin:
    discovery-client-enabled: false
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.61.56.79:3306/guli_pms?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=True
    username: yuyuoped
    password: 123123
    hikari:
      max-lifetime: 60000
  redis:
    port: 6379
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:*.xml
  type-aliases-package: com.yuyuoped.gmall.pms.entity
  global-config:
    db-config:
      id-type: auto
seata:
  tx-service-group: gmall-tx-group
