server:
  port: 18084
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8722
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.61.56.79:3306/guli_ums?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=True
    username: yuyuoped
    password: 123123
    hikari:
      max-lifetime: 30000
  redis:
    host: 182.61.56.79
    port: 6379
mybatis-plus:
  mapper-locations: classpath:*.xml
  type-aliases-package: com.yuyuoped.gmall.ums.entity
  global-config:
    db-config:
      id-type: auto
feign:
  sentinel:
    enabled: true